/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["'Inter'", "sans-serif"],
        label: ["'Inter'", "sans-serif"],
      },
      colors: {
        base: {
          950: "#08131b",
          900: "#0d1d27",
          850: "#132734",
          800: "#183243",
          700: "#234458",
          400: "#7eb7d1",
          300: "#a7d3e5",
          200: "#d3eef7",
          100: "#eef9fc",
        },
        accent: {
          orange: "#ff8a3d",
          coral: "#ff6f61",
          lime: "#c4ff75",
          gold: "#ffd66b",
        },
        "on-secondary-container": "#004a7d",
        "on-error": "#ffefec",
        "outline-variant": "#d393fc",
        tertiary: "#485c80",
        "surface-tint": "#894d00",
        "on-tertiary-fixed": "#1f3456",
        "secondary-fixed": "#b3d4ff",
        "inverse-on-surface": "#c183ea",
        "tertiary-fixed": "#bed2fd",
        "on-primary-fixed": "#231000",
        primary: "#894d00",
        "on-tertiary": "#eff2ff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#7b40a3",
        "inverse-primary": "#ff9300",
        "on-background": "#4a0672",
        "on-secondary-fixed": "#00365e",
        "secondary-container": "#b3d4ff",
        "surface-dim": "#ecc7ff",
        "primary-container": "#ff9300",
        "on-primary-fixed-variant": "#552e00",
        "tertiary-fixed-dim": "#b0c4ee",
        "surface-container-high": "#f4daff",
        "primary-fixed": "#ff9300",
        "tertiary-dim": "#3c5074",
        "on-error-container": "#520c00",
        "error-container": "#f95630",
        error: "#b02500",
        "on-primary-container": "#482600",
        outline: "#995dc1",
        background: "#fff3ff",
        "surface-bright": "#fff3ff",
        "error-dim": "#b92902",
        "surface-container": "#f7e1ff",
        "primary-dim": "#784200",
        secondary: "#005e9e",
        "surface-container-highest": "#f0d2ff",
        "on-surface": "#4a0672",
        surface: "#fff3ff",
        "on-secondary": "#edf3ff",
        "on-tertiary-container": "#33486b",
        "on-secondary-fixed-variant": "#00538c",
        "surface-container-low": "#fcecff",
        "surface-variant": "#f0d2ff",
        "secondary-fixed-dim": "#98c7ff",
        "inverse-surface": "#1b002f",
        "primary-fixed-dim": "#ec8800",
        "on-tertiary-fixed-variant": "#3d5175",
        "on-primary": "#fff0e6",
        "secondary-dim": "#00528b",
        "tertiary-container": "#bed2fd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        glass: "0 20px 60px rgba(3, 12, 19, 0.22)",
      },
      backgroundImage: {
        "hero-mesh":
          "radial-gradient(circle at top left, rgba(255,138,61,0.36), transparent 32%), radial-gradient(circle at 82% 12%, rgba(126,183,209,0.28), transparent 28%), linear-gradient(135deg, #08131b 0%, #132734 55%, #183243 100%)",
      },
      animation: {
        float: "float 8s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
    },
  },
  plugins: [],
};
